# Generated by Django 5.2.10 on 2026-01-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ventas_detalleventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='boleta_origen',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleVentas',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
