# Generated by Django 5.2.6 on 2026-02-02 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ventas_boleta_origen_remove_ventas_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('A', 'Almacén')], default='A', max_length=2)),
                ('destino', models.CharField(choices=[('S1', 'Tienda S1'), ('S2', 'Tienda S2'), ('S3', 'Tienda S3')], max_length=2)),
                ('ejecutado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
