# Generated by Django 5.2.6 on 2026-02-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_caja_cajadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajadetalle',
            name='caja',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='CajaDetalle',
        ),
    ]
