# Generated by Django 5.2.6 on 2026-02-12 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente'),
        ('ventas', '0011_venta_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={},
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('abierta', True)), fields=('ubicacion',), name='unica_caja_abierta_por_ubicacion'),
        ),
    ]
