# Generated by Django 5.2.6 on 2026-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Sistema LEO', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='web/logo/')),
                ('banner_titulo', models.CharField(default='¡Bienvenidos a nuestra tienda!', max_length=200)),
                ('banner_subtitulo', models.TextField(default='Las mejores ofertas de la temporada.')),
                ('banner_imagen', models.ImageField(blank=True, null=True, upload_to='web/banners/')),
                ('color_primario', models.CharField(default='#0d6efd', help_text='Código Hexadecimal (ej: #0d6efd)', max_length=7)),
                ('whatsapp', models.CharField(default='+51999888777', max_length=20)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración General de la Web',
            },
        ),
    ]
