# Generated by Django 5.2.6 on 2026-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='banner',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(upload_to='banners/', verbose_name='Imagen del Banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (Opcional)'),
        ),
    ]
