# Generated by Django 5.2.6 on 2026-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_banner_options_banner_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionweb',
            name='direccion',
            field=models.CharField(default='Av. Ejemplo 123, Ciudad', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionweb',
            name='email',
            field=models.EmailField(default='contacto@tu-tienda.com', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionweb',
            name='horario_atencion',
            field=models.CharField(default='Lunes a Sábado: 9am - 8pm', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionweb',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionweb',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
